spring:
  application:
    name: appointment-scheduling-api
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: guidance
    password: Changeme0
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
jwt:
  secret : 'thebigbrownfoxjumpsoverthelazydog'

firebase:
  project-id: appointment-notification-cc54d
  service-account-file: firebase-service-account.json

server:
  address: 0.0.0.0
  port: 8080

