spring:
  application:
    name: appointment-scheduling-api
    base-url: "http://localhost:8080"
    frontend-url: "http://localhost:5173"
    endpoints:
      password-reset-verify: "/user/password-reset/verify"

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: guidance
    password: Changeme0
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret : 'thebigbrownfoxjumpsoverthelazydog'

firebase:
  project-id: appointment-notification-cc54d
  service-account-file: firebase-service-account.json

server:
  address: 0.0.0.0
  port: 8080

password:
  reset:
    token:
      expiration:
        hours: 24
admin:
  default:
    username: admin
    password: 123123
    email: admin@guidance.edu
  auto-create: true

appointment:
  max-pending-per-student: 1